// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdAkMzXNsgW6uIt3jaP4O22_zjd1JjtM',
    appId: '1:486258353737:web:aaca26e9dcf7c485458198',
    messagingSenderId: '486258353737',
    projectId: 'kanabeza-88d42',
    authDomain: 'kanabeza-88d42.firebaseapp.com',
    storageBucket: 'kanabeza-88d42.firebasestorage.app',
    measurementId: 'G-X91YWHWY1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-ZD3uaKcV3WuPxxideOhCMkCA_Z08j0',
    appId: '1:486258353737:android:3af456ca92602626458198',
    messagingSenderId: '486258353737',
    projectId: 'kanabeza-88d42',
    storageBucket: 'kanabeza-88d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXyJPyFRY3jf4b7-SzGu7LEuELp87jpA',
    appId: '1:486258353737:ios:1e001d5ac6424f8a458198',
    messagingSenderId: '486258353737',
    projectId: 'kanabeza-88d42',
    storageBucket: 'kanabeza-88d42.firebasestorage.app',
    iosClientId: '486258353737-6gcmo6nkqllfllt5soq9297e416b7889.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanabeza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXyJPyFRY3jf4b7-SzGu7LEuELp87jpA',
    appId: '1:486258353737:ios:1e001d5ac6424f8a458198',
    messagingSenderId: '486258353737',
    projectId: 'kanabeza-88d42',
    storageBucket: 'kanabeza-88d42.firebasestorage.app',
    iosClientId: '486258353737-6gcmo6nkqllfllt5soq9297e416b7889.apps.googleusercontent.com',
    iosBundleId: 'com.example.kanabeza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZdAkMzXNsgW6uIt3jaP4O22_zjd1JjtM',
    appId: '1:486258353737:web:247fb47df2a903de458198',
    messagingSenderId: '486258353737',
    projectId: 'kanabeza-88d42',
    authDomain: 'kanabeza-88d42.firebaseapp.com',
    storageBucket: 'kanabeza-88d42.firebasestorage.app',
    measurementId: 'G-SVFG16QBBH',
  );
}
